trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

stages:

- stage: 'Build'
  variables:
    - group: NuGetVariables
    major: '1'
    minor: '0'
    revision: $[counter(variables['minor'], 1)] 
    nugetVersion: '$(major).$(minor).$(revision)'

  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      displayName: Setup .NET 6.0
      inputs:
        packageType: "sdk"
        version: "6.0.x"

    - task: DotNetCoreCLI@2
      displayName: Restore dependencies
      inputs:
        command: 'restore'
        projects: 'KoloDev.GDS.QA.Accelerator.sln'

    - task: DotNetCoreCLI@2
      displayName: Build project
      inputs:
        command: 'build'
        projects: 'KoloDev.GDS.QA.Accelerator.sln'
        arguments: '/p:Configuration=Release -p:Version=$(nugetVersion)'

    - task: CopyFiles@2
      displayName: Copy packages to pipeline artifacts
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.nupkg
          **/*.snupkg
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts'

    - script: |
          nuget push $(Build.ArtifactStagingDirectory)/artifacts/**/*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey $(NUGET_API_KEY)
      displayName: "Push packages to NuGet"
    - publish: '$(Build.ArtifactStagingDirectory)/artifacts'
      displayName: Publish pipeline artifacts
      artifact: 'artifacts'
